### ISSUE TITLE
Etched crashes with optifiabric

### ISSUE THREAD

**Issue by MuhannadYT** [jaacksondev/etched#7] opened 2021-06-29 16:36 UTC
Minecraft crashes when etched and optifabric are loaded.
I tried removing optifabric and it worked. But please fix this issue, as I can't play Minecraft without optifine (for many reasons such as dynamic lighting and a lot of other features) Thank you

**Comment by jaacksondev** [comment] 2021-06-29 23:42
Duplicate of #6

**Closed by jaacksondev** 2021-06-29 23:42 UTC
