### ISSUE TITLE
Fabric 1.20.1?

### ISSUE THREAD

**Issue by Mxpea** [jaacksondev/etched#109] opened 2024-08-12 12:51 UTC

**Comment by Mxpea** [comment] 2024-08-12 12:52
please update I need it

**Comment by Redfan2** [comment] 2024-08-12 16:07
They dropped support for it, however there is a unofficial port: https://github.com/unilock/etched/tree/fabric/1.20.x

**Comment by Ocelot5836** [comment] 2024-12-17 06:07
Duplicate of #82

**Closed as not planned by Ocelot5836** 2024-12-17 06:07 UTC
